<?xml version="1.0" ?>

<robot name="laser" xmlns:xacro="http://www.ros.org/wiki/xacro">
   <!-- include  -->
    <xacro:include filename="$(find laser_description)/urdf/robot_parameters.xacro" />

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <link name="base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 -0.0015"/>
            <geometry>
                <box size="${metal_plate_length} ${metal_plate_width} 0.003"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    
    <!-- Rotary Table -->

    <link name="rotary_base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://laser_description/meshes/rotary_base_link.STL"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="base_link__rotary_base" type="fixed">
        <axis xyz="0 0 1" />
        <origin rpy="0 0 0" xyz="0.020 0 0"/>
        <parent link="base_link"/>
        <child link="rotary_base"/>
    </joint>

    <link name="rotary_base_invisible">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0 0 0"/>
            </geometry>
        </visual>
    </link>

    <joint name="rotary_base__rotary_base_invisible" type="fixed">
        <origin rpy="1.57 0 0" xyz="0 0 0"/>
        <parent link="rotary_base"/>
        <child link="rotary_base_invisible"/>
    </joint>

    <link name="rotary_middle">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://laser_description/meshes/rotary_middle_link.STL"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="A" type="revolute">
        <axis xyz="1 0 0" />
        <limit effort="1000.0" lower="${theta4_limit}" upper="0" velocity="1" />
        <origin rpy="0 0 0" xyz="0 ${metal_plate_to_rotary_center_height} 0"/>
        <parent link="rotary_base_invisible"/> 
        <child link="rotary_middle"/>
    </joint>

    <!-- rotary_top = Work Coordinate Frame -->
    <link name="W">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://laser_description/meshes/rotary_top_link.STL"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>

    <joint name="B" type="revolute">
        <axis xyz="0 0 1" />
        <limit effort="1000.0" lower="${theta5_limit}" upper="0" velocity="1" />
        <origin rpy="0 0 0" xyz="0 0 ${rotary_center_to_rotary_top}"/>
        <parent link="rotary_middle"/>
        <child link="W"/>
    </joint>

    <!-- Linear Stage -->

    <link name="y_box1">
        <visual>
            <origin rpy="0 0 0" xyz="0 ${y_rail_length/2} 0"/>
            <geometry>
                <box size="${rail_width} ${y_rail_length} ${rail_width}"/>
            </geometry>
        </visual>
    </link>

    <joint name="Z" type="prismatic">
        <axis xyz="0 0 1" />
        <limit effort="1000.0" lower="${d3_limit}" upper="0" velocity="1" />
        <origin rpy="0 0 0" xyz="${rotary_center_to_linear_stage_x} ${rotary_center_to_linear_stage_y} ${metal_plate_to_rotary_center_height+rotary_center_to_linear_stage_z}"/>
        <parent link="rotary_base"/>
        <child link="y_box1"/>
    </joint>

    <link name="y_box2">
        <visual>
            <origin rpy="0 0 0" xyz="0 ${y_rail_length/2} 0"/>
            <geometry>
                <box size="${rail_width} ${y_rail_length} ${rail_width}"/>
            </geometry>
        </visual>
    </link>

    <joint name="y_box1__y_box2" type="fixed">
        <origin rpy="0 0 0" xyz="${-x_rail_length-rail_width} 0 0"/>
        <parent link="y_box1"/>
        <child link="y_box2"/>
    </joint>

    <link name="x_box">
        <visual>
            <origin rpy="0 0 0" xyz="${x_rail_length/2} 0 0"/>
            <geometry>
                <box size="${x_rail_length} ${rail_width} ${rail_width}"/>
            </geometry>
        </visual>
    </link>

    <joint name="Y" type="prismatic">
        <axis xyz="0 1 0" />
        <limit effort="1000.0" lower="${d2_limit}" upper="0" velocity="1" />
        <origin rpy="0 0 3.1415" xyz="${-rail_width/2} 0.09 ${rail_width}"/>
        <parent link="y_box1"/>
        <child link="x_box"/>
    </joint>
    
    <!-- tool = Tool Coordinates Frame -->
    <link name="T">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${laser_height/2}"/>
            <geometry>
                <cylinder radius="${laser_rad}" length="${laser_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>

    <joint name="X" type="prismatic">
        <axis xyz="1 0 0" />
        <limit effort="1000.0" lower="${d1_limit}" upper="0" velocity="1" />
        <origin rpy="0 0 3.1415" xyz="0.063 ${rail_width/2+laser_rad} ${rail_width/2-laser_height}"/>
        <parent link="x_box"/>
        <child link="T"/>
    </joint>
</robot>