<?xml version="1.0" ?>

<robot name="laser" xmlns:xacro="http://www.ros.org/wiki/xacro">
   <!-- include  -->
    <xacro:include filename="$(find laser_description)/urdf/robot_parameters.xacro" />

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <link name="base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 -0.0015"/>
            <geometry>
                <box size="${base_link_length} ${base_link_width} 0.003"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    
    <link name="rotary_base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://laser_description/meshes/rotary_base_link.STL"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="base_link__rotary_base" type="fixed">
        <axis xyz="0 0 1" />
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="base_link"/>
        <child link="rotary_base"/>
    </joint>

    <link name="rotary_invisible">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0 0 0"/>
            </geometry>
        </visual>
    </link>

    <joint name="rotary_base__rotary_invisible" type="fixed">
        <origin rpy="1.57 0 0" xyz="0 0 0"/>
        <parent link="rotary_base"/>
        <child link="rotary_invisible"/>
    </joint>

    <link name="rotary_middle">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://laser_description/meshes/rotary_middle_link.STL"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="rotary_base__rotary_middle" type="revolute">
        <axis xyz="1 0 0" />
        <limit effort="1000.0" lower="-2.356" upper="0" velocity="0.5" />
        <origin rpy="0 0 0" xyz="0 0.08 0"/>
        <parent link="rotary_invisible"/> 
        <child link="rotary_middle"/>
    </joint>

    <link name="rotary_top">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://laser_description/meshes/rotary_top_link.STL"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>

    <joint name="rotary_middle__rotary_top" type="revolute">
        <axis xyz="0 0 1" />
        <limit effort="1000.0" lower="-314" upper="0" velocity="0.5" />
        <origin rpy="0 0 0" xyz="0 0 0.120"/>
        <parent link="rotary_middle"/>
        <child link="rotary_top"/>
    </joint>

    <!-- <joint name="base_link__tool" type="revolute">
        <axis xyz="0 0 1" />
        <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />
        <origin rpy="0 0 0" xyz="2.0 1.2 0.5"/>
        <parent link="base_link"/>
        <child link="tool"/>
    </joint> -->

    <link name="y_box1">
        <visual>
            <origin rpy="0 0 0" xyz="0 ${y_rail_length/2} 0"/>
            <geometry>
                <box size="${rail_width} ${y_rail_length} ${rail_width}"/>
            </geometry>
        </visual>
    </link>

    <joint name="base_link__y_box1" type="prismatic">
        <axis xyz="0 0 1" />
        <limit effort="1000.0" lower="${-z_joint_limit}" upper="0" velocity="0.5" />
        <origin rpy="0 0 0" xyz="${x_rail_length/2+rail_width} ${base_link_width-y_rail_length} 0.3"/>
        <parent link="base_link"/>
        <child link="y_box1"/>
    </joint>

    <link name="y_box2">
        <visual>
            <origin rpy="0 0 0" xyz="0 ${y_rail_length/2} 0"/>
            <geometry>
                <box size="${rail_width} ${y_rail_length} ${rail_width}"/>
            </geometry>
        </visual>
    </link>

    <joint name="y_box1__y_box2" type="fixed">
        <origin rpy="0 0 0" xyz="${-x_rail_length-rail_width} 0 0"/>
        <parent link="y_box1"/>
        <child link="y_box2"/>
    </joint>

    <link name="x_box">
        <visual>
            <origin rpy="0 0 0" xyz="${x_rail_length/2} 0 0"/>
            <geometry>
                <box size="${x_rail_length} ${rail_width} ${rail_width}"/>
            </geometry>
        </visual>
    </link>

    <joint name="y_box1__x_box" type="prismatic">
        <axis xyz="0 1 0" />
        <limit effort="1000.0" lower="-0.26" upper="0" velocity="0.5" />
        <origin rpy="0 0 3.1415" xyz="${-rail_width/2} 0.09 ${rail_width}"/>
        <parent link="y_box1"/>
        <child link="x_box"/>
    </joint>
    
    <link name="tool">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${laser_height/2}"/>
            <geometry>
                <cylinder radius="${laser_rad}" length="${laser_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>

    <joint name="x_box__tool" type="prismatic">
        <axis xyz="1 0 0" />
        <limit effort="1000.0" lower="-0.26" upper="0" velocity="0.5" />
        <origin rpy="0 0 3.1415" xyz="0.063 ${rail_width/2+laser_rad} ${rail_width/2-laser_height}"/>
        <parent link="x_box"/>
        <child link="tool"/>
    </joint>
</robot>